version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_CE_VERSION}
    restart: always
    container_name: gitlab
    hostname: "${GITLAB_HOST}"
    environment:
      - TZ=${TZ}
    volumes:
      - './volumes/config:/etc/gitlab'
      - './volumes/logs:/var/log/gitlab'
      - './volumes/data:/var/opt/gitlab'
    ports:
      - ${GITLAB_NGINX_INSECURED_PORT}:80
      - ${GITLAB_NGINX_SECURED_PORT}:443
    depends_on:
      - redis
      - postgres
    networks:
      - default

  runner:
    image: gitlab/gitlab-runner:${GITLAB_RUNNER_VERSION}
    restart: always
    container_name: gitlab_runner
    environment:
      - CI_SERVER_URL=https://${GITLAB_HOST}:${GITLAB_NGINX_SECURED_PORT}/
      - REGISTRATION_TOKEN=${GITLAB_DEFAULT_TOKEN}
    volumes:
      - ./volumes/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock:rw

  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    container_name: gitlab_postgresql
    # https://github.com/docker-library/docs/tree/master/postgres#environment-variables
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitlabhq_production
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    container_name: gitlab_redis
    command:
      - --loglevel warning
    volumes:
      - ./volumes/redis:/var/lib/redis

